name: Prod

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: '14'
    - name: set AWS Keys to environment and push to beta bucket
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        DIST_ID: ${{secrets.PROD_DIST_ID}}
        RELIC_ACCOUNT_ID: ${{secrets.RELIC_ACCOUNT_ID}}
        RELIC_TRUST_KEY: ${{secrets.RELIC_TRUST_KEY}}
        RELIC_AGENT_ID: ${{secrets.RELIC_AGENT_ID}}
        RELIC_LICENSE_KEY: ${{secrets.RELIC_LICENSE_KEY}}
        RELIC_APPLICATION_ID: ${{secrets.RELIC_APPLICATION_ID}}
        PM_TECH: ${{secrets.PM_TECH}}
      run: |
        npm install
        GATSBY_ACTIVE_ENV=production npm run build && node_modules/s3-deploy/bin/s3-deploy './public/**' --cwd './public/' --bucket postman-covid-19-prod --private --deleteRemoved --distId $DIST_ID --invalidate '/*'

